apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-a
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sre-platform
  selector:
    matchLabels:
      app: service-a
  endpoints:
    - targetPort: 3000
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-b
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sre-platform
  selector:
    matchLabels:
      app: service-b
  endpoints:
    - targetPort: 5000
      path: /metrics
      interval: 15s
