apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: sre-platform
spec:
  type: NodePort
  selector:
    app: service-a
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
